// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(public)/(auth)/login_page.dart' as a5;
import 'app/(public)/app_page.dart' as a4;
import 'app/(public)/home_page.dart' as a0;
import 'app/(public)/products/[id]/edit_page.dart' as a2;
import 'app/(public)/products/create_page.dart' as a1;
import 'app/(public)/products/products_page.dart' as a3;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/products/create',
        uri: Uri.parse('/products/create'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.ProductNewPage(),
        ),
      ),
      RouteEntity(
        key: '/products/[id]/edit',
        uri: Uri.parse('/products/[id]/edit'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.ProductEditPage(),
        ),
      ),
      RouteEntity(
        key: '/products',
        uri: Uri.parse('/products'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.ProductIndexPage(),
        ),
      ),
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.AppPage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a5.LoginPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  products: (
    path: '/products',
    create: '/products/create',
    $id: (
      path: '/products/[id]',
      edit: '/products/[id]/edit',
    ),
  ),
  login: '/login',
);
